(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  const checks = [];
  const check = (condition, message) => { assert(condition, message); checks.push(message); };

  check(document.querySelector('#profileName')?.textContent.length > 0, 'initial state rendered');
  check(document.querySelector('.titlebar .version')?.textContent.trim() === '4.5', 'version 4.5 shell is rendered');
  document.querySelector('#settingsButton').click();
  check(document.querySelectorAll('#settingLocale option').length === 12, 'language selector exposes system detection and eleven language packs');
  document.querySelector('#settingLocale').value = 'en';
  document.querySelector('#settingLocale').dispatchEvent(new Event('change', { bubbles: true }));
  await wait(80);
  check(document.documentElement.lang === 'en' && document.querySelector('[data-nav="dashboard"] .nav-label').textContent.trim() === 'Home', 'English locale applies without restarting');
  check(!/[ぁ-んァ-ヶ]/.test(document.querySelector('#settingsModal').innerText), 'English settings contain no residual Japanese UI copy');
  document.querySelector('#settingLocale').value = 'ar';
  document.querySelector('#settingLocale').dispatchEvent(new Event('change', { bubbles: true }));
  await wait(80);
  check(document.documentElement.dir === 'rtl' && document.querySelector('[data-nav="focus"] .nav-label').textContent.trim() === 'التركيز', 'Arabic locale enables RTL presentation');
  document.querySelector('#settingLocale').value = 'ja';
  document.querySelector('#settingLocale').dispatchEvent(new Event('change', { bubbles: true }));
  await wait(80);
  check(document.documentElement.lang === 'ja' && document.documentElement.dir === 'ltr', 'Japanese locale restores the source interface');
  document.querySelector('[data-close-settings]').click();
  check(document.body.dataset.design === 'material3', 'Material Design 3 mode is active');
  check([...document.styleSheets].some((sheet) => sheet.href?.endsWith('/material3.css')), 'Material Design 3 stylesheet is loaded');
  check(getComputedStyle(document.documentElement).getPropertyValue('--md-sys-color-primary').trim().length > 0, 'Material semantic color roles are defined');
  check(document.querySelectorAll('.primary-nav .nav-label').length === 8, 'navigation rail exposes persistent labels');
  check(parseFloat(getComputedStyle(document.querySelector('#quickAddButton')).borderRadius) >= 16, 'extended action uses Material shape');
  check(document.querySelector('#quickAddButton').getBoundingClientRect().height >= 48, 'primary action has an accessible interaction target');
  check(document.querySelector('.primary-nav .nav-button').getBoundingClientRect().height >= 48, 'navigation targets retain accessible height');
  check(document.querySelector('.primary-nav [aria-current="page"]')?.dataset.nav === 'dashboard', 'active destination is announced semantically');
  check(getComputedStyle(document.querySelector('.panel')).backdropFilter === 'none', 'surfaces use tonal hierarchy instead of glass blur');
  check(document.querySelector('#dashboardView').scrollWidth <= document.querySelector('#dashboardView').clientWidth + 1, 'dashboard has no horizontal overflow');
  const before = document.querySelectorAll('#dashboardTaskList .task-row').length;

  document.querySelector('[data-nav="missions"]').click();
  document.querySelector('#projectAddButton').click();
  check(document.querySelector('#projectModal').classList.contains('open'), 'project modal opens');
  document.querySelector('#projectName').value = 'Horizon Project';
  document.querySelector('#projectDescription').value = '4.5の統合操作を検証';
  document.querySelector('#projectColor').value = 'cyan';
  document.querySelector('#projectForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(130);
  check([...document.querySelectorAll('#projectStrip .project-card')].some((card) => card.textContent.includes('Horizon Project')), 'project portfolio creates a project');
  const horizonProjectId = [...document.querySelector('#projectFilterSelect').options].find((option) => option.textContent === 'Horizon Project').value;
  document.querySelector(`[data-project-edit="${horizonProjectId}"]`).click();
  document.querySelector('#projectDescription').value = '更新された4.5プロジェクト';
  document.querySelector('#projectForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(100);
  check([...document.querySelectorAll('#projectStrip .project-card')].some((card) => card.textContent.includes('更新された4.5プロジェクト')), 'project portfolio edits project details');
  document.querySelector('#projectAddButton').click();
  document.querySelector('#projectName').value = 'Disposable Project';
  document.querySelector('#projectForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(100);
  const disposableId = [...document.querySelector('#projectFilterSelect').options].find((option) => option.textContent === 'Disposable Project').value;
  document.querySelector(`[data-project-edit="${disposableId}"]`).click();
  document.querySelector('#projectDeleteButton').click();
  await wait(100);
  check(![...document.querySelectorAll('#projectStrip .project-card')].some((card) => card.textContent.includes('Disposable Project')), 'project can be deleted without deleting missions');
  [...document.querySelectorAll('#toastRegion .toast button')].at(-1).click();
  await wait(100);
  check([...document.querySelectorAll('#projectStrip .project-card')].some((card) => card.textContent.includes('Disposable Project')), 'deleted project can be restored');
  document.querySelector('[data-nav="dashboard"]').click();

  document.querySelector('#quickAddButton').click();
  check(document.querySelector('#taskModal').classList.contains('open'), 'task modal opens');
  document.querySelector('#taskTitle').value = 'UIスモークテスト・ミッション';
  document.querySelector('#taskDetail').value = '自動操作で追加された確認用データ';
  document.querySelector('#taskRecurrence').value = 'daily';
  document.querySelector('#taskEstimate').value = '45';
  document.querySelector('#taskProject').value = horizonProjectId;
  document.querySelector('#taskStatus').value = 'next';
  document.querySelector('#subtaskInput').value = '仕様を確認する';
  document.querySelector('#subtaskAddButton').click();
  document.querySelector('#subtaskInput').value = '結果を記録する';
  document.querySelector('#subtaskAddButton').click();
  check(document.querySelectorAll('#subtaskDraftList .subtask-draft').length === 2, 'subtasks can be drafted');
  document.querySelector('#taskForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(150);
  check(document.querySelectorAll('#dashboardTaskList .task-row').length === before + 1, 'task creation updates dashboard');
  check(document.querySelector('#navigatorTitle').textContent.trim().length > 0 && !document.querySelector('#navigatorFocusButton').disabled, 'smart navigator recommends a mission');

  document.querySelector('[data-nav="missions"]').click();
  const detailedTask = [...document.querySelectorAll('#missionTaskList .task-row')].find((row) => row.textContent.includes('UIスモークテスト'));
  check(detailedTask?.querySelectorAll('.subtask-item').length === 2 && detailedTask.textContent.includes('毎日') && detailedTask.textContent.includes('45 MIN') && detailedTask.textContent.includes('Horizon Project'), 'mission view shows project, subtasks, recurrence, and estimate');
  detailedTask.querySelector('.subtask-item').click();
  await wait(120);
  const updatedDetailedTask = [...document.querySelectorAll('#missionTaskList .task-row')].find((row) => row.textContent.includes('UIスモークテスト'));
  check(updatedDetailedTask.querySelector('.subtask-item').classList.contains('done'), 'subtask toggles directly from mission view');
  updatedDetailedTask.querySelector('[data-action="snooze"]').click();
  await wait(120);
  const snoozedTask = [...document.querySelectorAll('#missionTaskList .task-row')].find((row) => row.textContent.includes('UIスモークテスト'));
  check(snoozedTask.textContent.includes('明日'), 'mission can be shifted by one day');
  [...document.querySelectorAll('#toastRegion .toast button')].at(-1).click();
  await wait(120);
  const restoredTask = [...document.querySelectorAll('#missionTaskList .task-row')].find((row) => row.textContent.includes('UIスモークテスト'));
  check(restoredTask.textContent.includes('今日'), 'shifted mission can be restored');
  document.querySelector('#projectFilterSelect').value = horizonProjectId;
  document.querySelector('#projectFilterSelect').dispatchEvent(new Event('change', { bubbles: true }));
  check([...document.querySelectorAll('#missionTaskList .task-row')].every((row) => row.textContent.includes('Horizon Project')), 'project filter scopes the mission list');
  document.querySelector('#missionViewButton').click();
  check(document.querySelectorAll('#missionBoard .board-column').length === 4, 'mission board renders four workflow states');
  let boardTask = [...document.querySelectorAll('#missionBoard .board-card')].find((card) => card.textContent.includes('UIスモークテスト'));
  check(boardTask?.getAttribute('draggable') === 'true', 'mission cards are draggable');
  const dragData = new DataTransfer();
  boardTask.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer: dragData }));
  const waitingColumn = document.querySelector('[data-board-status="waiting"]');
  waitingColumn.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: dragData }));
  waitingColumn.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: dragData }));
  await wait(100);
  check([...document.querySelectorAll('[data-board-status="waiting"] .board-card')].some((card) => card.textContent.includes('UIスモークテスト')), 'board drag moves a mission to waiting');
  boardTask = [...document.querySelectorAll('[data-board-status="waiting"] .board-card')].find((card) => card.textContent.includes('UIスモークテスト'));
  boardTask.querySelector('[data-board-action="previous"]').click();
  await wait(100);
  check([...document.querySelectorAll('[data-board-status="next"] .board-card')].some((card) => card.textContent.includes('UIスモークテスト')), 'board moves a mission back to next actions');
  document.querySelector('[data-nav="dashboard"]').click();

  const created = [...document.querySelectorAll('#dashboardTaskList .task-row')].find((row) => row.textContent.includes('UIスモークテスト'));
  check(Boolean(created), 'created task is visible');
  created.querySelector('[data-action="toggle"]').click();
  await wait(180);
  check(![...document.querySelectorAll('#dashboardTaskList .task-row')].some((row) => row.textContent.includes('UIスモークテスト')), 'task completion updates active list');
  const recurringState = await window.asteria.load();
  const recurringTasks = recurringState.tasks.filter((task) => task.title === 'UIスモークテスト・ミッション');
  check(recurringTasks.some((task) => task.done) && recurringTasks.some((task) => !task.done), 'recurring completion creates the next mission');
  check(recurringTasks.find((task) => !task.done)?.subtasks.every((subtask) => !subtask.done), 'recurring mission resets its subtasks');
  check(recurringTasks.find((task) => !task.done)?.projectId === horizonProjectId, 'recurring mission retains its project');

  document.querySelector('[data-nav="logbook"]').click();
  check(document.querySelector('#logbookView').classList.contains('active'), 'logbook navigation works');
  const notes = document.querySelector('#fullNotes');
  notes.value = '# 自動テスト\n\n**保存とプレビュー**';
  notes.dispatchEvent(new Event('input', { bubbles: true }));
  await wait(80);
  check(document.querySelector('#notePreview').textContent.includes('保存とプレビュー'), 'note preview updates');

  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  check(document.querySelector('#commandPalette').classList.contains('open'), 'command palette shortcut works');
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  check(!document.querySelector('#commandPalette').classList.contains('open'), 'escape closes command palette');

  document.querySelector('[data-nav="planner"]').click();
  check(document.querySelector('#plannerView').classList.contains('active'), 'planner navigation works');
  document.querySelector('[data-planner-mode="week"]').click();
  check(document.querySelector('#plannerView').classList.contains('week-mode') && document.querySelectorAll('#weekGrid .week-day').length === 7, 'weekly cockpit renders seven days');
  document.querySelector(`#weekGrid [data-week-date="${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(new Date().getDate()).padStart(2, '0')}"]`).click();
  check(!document.querySelector('#plannerView').classList.contains('week-mode'), 'weekly cockpit opens a selected day');
  document.querySelector('[data-planner-mode="month"]').click();
  check(document.querySelector('#plannerView').classList.contains('month-mode') && document.querySelectorAll('#monthGrid .month-cell').length === 42, 'month calendar renders a six-week grid');
  document.querySelector('#monthGrid .month-cell.selected').click();
  check(!document.querySelector('#plannerView').classList.contains('month-mode'), 'month calendar opens the selected day');
  document.querySelector('#planAddButton').click();
  document.querySelector('#planTitle').value = '午後の設計セッション';
  document.querySelector('#planTime').value = '14:00';
  document.querySelector('#planReminder').value = '10';
  document.querySelector('#planForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(100);
  check([...document.querySelectorAll('#dayPlanList .plan-block')].some((row) => row.textContent.includes('午後の設計セッション')), 'planner creates a time block');
  const plan = [...document.querySelectorAll('#dayPlanList .plan-block')].find((row) => row.textContent.includes('午後の設計セッション'));
  check(plan.textContent.includes('10分前通知'), 'planner displays the reminder rule');
  document.querySelector('#planAddButton').click();
  document.querySelector('#planTitle').value = '重複確認ブロック';
  document.querySelector('#planTime').value = '14:15';
  document.querySelector('#planDuration').value = '30';
  document.querySelector('#planForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  await wait(100);
  check(document.querySelectorAll('#dayPlanList .plan-block.conflict').length === 2 && document.querySelector('#plannerAssist').classList.contains('conflict'), 'planner detects overlapping time blocks');
  const refreshedPlan = [...document.querySelectorAll('#dayPlanList .plan-block')].find((row) => row.textContent.includes('午後の設計セッション'));
  refreshedPlan.querySelector('[data-plan-action="toggle"]').click();
  check(document.querySelector('#plannerProgressText').textContent !== '0%', 'planner completion updates progress');
  const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1);
  document.querySelector('#plannerDateInput').value = `${tomorrow.getFullYear()}-${String(tomorrow.getMonth() + 1).padStart(2, '0')}-${String(tomorrow.getDate()).padStart(2, '0')}`;
  document.querySelector('#plannerDateInput').dispatchEvent(new Event('change', { bubbles: true }));
  document.querySelector('#autoPlanButton').click();
  await wait(130);
  const autoPlannedCount = document.querySelectorAll('#dayPlanList .plan-block.auto-planned').length;
  check(autoPlannedCount > 0, `orbit assist auto-plans missions into free time [count=${autoPlannedCount}; signal=${document.querySelector('#plannerAssistTitle').textContent}; toast=${[...document.querySelectorAll('#toastRegion .toast')].at(-1)?.textContent || 'none'}]`);
  check(document.querySelectorAll('#dayPlanList .plan-block.conflict').length === 0, 'auto-planned blocks avoid schedule conflicts');

  const visibleHabitDay = document.querySelector('#habitList [data-habit-date]');
  check(Boolean(visibleHabitDay), 'habit week is rendered');
  visibleHabitDay.click();
  check(visibleHabitDay.classList.contains('checked') || document.querySelector(`#habitList [data-habit-date="${visibleHabitDay.dataset.habitDate}"]`).classList.contains('checked'), 'habit completion toggles');

  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  document.querySelector('#commandSearch').value = '今日の最重要';
  document.querySelector('#commandSearch').dispatchEvent(new Event('input', { bubbles: true }));
  check(document.querySelector('#commandResults').textContent.includes('今日の最重要ミッション'), 'command palette searches missions');
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));

  document.querySelector('#settingsButton').click();
  check(parseFloat(getComputedStyle(document.querySelector('#settingsModal .modal')).borderRadius) >= 28, 'dialog uses Material extra-large shape');
  document.querySelector('[data-appearance="light"]').click();
  const lightBackground = getComputedStyle(document.body).getPropertyValue('--md-sys-color-background').trim();
  check(document.body.dataset.colorScheme === 'light' && document.querySelector('[data-appearance="light"]').getAttribute('aria-pressed') === 'true', 'light appearance applies and exposes selected state');
  document.querySelector('[data-appearance="dark"]').click();
  check(document.body.dataset.colorScheme === 'dark' && getComputedStyle(document.body).getPropertyValue('--md-sys-color-background').trim() !== lightBackground, 'dark appearance applies a distinct tonal surface');
  document.querySelector('[data-appearance="system"]').click();
  check(['light', 'dark'].includes(document.body.dataset.colorScheme) && document.querySelector('[data-appearance="system"]').getAttribute('aria-pressed') === 'true', 'system appearance resolves the Windows preference');
  document.querySelector('[data-theme-option="cyan"]').click();
  check(document.body.dataset.theme === 'cyan', 'theme switching works');
  const cyanPrimary = getComputedStyle(document.body).getPropertyValue('--md-sys-color-primary').trim();
  check(/^#[0-9a-f]{6}$/i.test(cyanPrimary), 'theme seed remaps Material color roles');
  const accentInput = document.querySelector('#settingAccentColor');
  accentInput.value = '#e91e63';
  accentInput.dispatchEvent(new Event('input', { bubbles: true }));
  const customPrimary = getComputedStyle(document.body).getPropertyValue('--md-sys-color-primary').trim();
  check(document.body.dataset.theme === 'custom' && customPrimary !== cyanPrimary && document.querySelector('#accentColorValue').value === '#E91E63', 'custom accent regenerates the complete color system');
  document.querySelector('[data-appearance="light"]').click();
  accentInput.value = '#ffe000';
  accentInput.dispatchEvent(new Event('input', { bubbles: true }));
  const luminance = (hex) => {
    const channels = hex.match(/[a-f\d]{2}/gi).map((part) => parseInt(part, 16) / 255).map((value) => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4);
    return .2126 * channels[0] + .7152 * channels[1] + .0722 * channels[2];
  };
  const contrast = (a, b) => { const values = [luminance(a), luminance(b)].sort((x, y) => y - x); return (values[0] + .05) / (values[1] + .05); };
  const yellowRoles = getComputedStyle(document.body);
  check(contrast(yellowRoles.getPropertyValue('--md-sys-color-on-primary').trim(), yellowRoles.getPropertyValue('--md-sys-color-primary').trim()) >= 4.5, 'arbitrary bright accent preserves AA primary-button contrast');
  accentInput.value = '#e91e63';
  accentInput.dispatchEvent(new Event('input', { bubbles: true }));
  document.querySelector('#settingMotionIntensity').value = 'gentle';
  document.querySelector('#settingMotionIntensity').dispatchEvent(new Event('change', { bubbles: true }));
  check(document.body.dataset.motion === 'gentle', 'gentle Material motion mode applies');
  document.querySelector('#settingReducedMotion').click();
  check(document.body.classList.contains('reduced-motion'), 'reduced motion setting works');
  document.querySelector('[data-close-settings]').click();

  document.querySelector('[data-nav="nexus"]').click();
  check(document.querySelector('#nexusView').classList.contains('active'), 'NEXUS navigation works');
  check(document.querySelectorAll('#automationList .automation-card').length === 5, 'NEXUS provides five curated automation rules');
  check(document.querySelectorAll('#templateGrid .template-card').length === 4, 'NEXUS provides four curated blueprints');
  const overdueToggle = document.querySelector('[data-auto-toggle="auto-overdue-priority"]');
  overdueToggle.click();
  check(overdueToggle.getAttribute('aria-pressed') === 'true' || document.querySelector('[data-auto-toggle="auto-overdue-priority"]').getAttribute('aria-pressed') === 'true', 'automation can be explicitly enabled');
  document.querySelector('[data-auto-toggle="auto-overdue-priority"]').click();
  check(document.querySelector('[data-auto-toggle="auto-overdue-priority"]').getAttribute('aria-pressed') === 'false', 'automation can be paused');
  document.querySelector('[data-auto-run="auto-today-priority"]').click();
  await wait(130);
  check(document.querySelectorAll('#automationHistory .automation-history-row').length === 1, 'manual automation records an auditable run');
  document.querySelector('#addAutomationButton').click();
  check(document.querySelector('#automationModal').classList.contains('open'), 'custom automation composer opens');
  document.querySelector('#automationName').value = 'No-date capture';
  document.querySelector('#automationCondition').value = 'no_due_open';
  document.querySelector('#automationAction').value = 'set_due_today';
  document.querySelector('#automationForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  check([...document.querySelectorAll('#automationList .automation-card')].some((card) => card.textContent.includes('No-date capture')), 'custom automation rule can be created');

  document.querySelector('[data-nexus-tab="templates"]').click();
  check(document.querySelector('#nexusTemplatePanel').classList.contains('active'), 'blueprint tab switches with semantic selected state');
  const beforeBlueprint = await window.asteria.load();
  document.querySelector('[data-template-deploy="template-deep-work"]').click();
  await wait(180);
  const afterBlueprint = await window.asteria.load();
  check(afterBlueprint.tasks.length === beforeBlueprint.tasks.length + 3 && afterBlueprint.projects.length === beforeBlueprint.projects.length + 1, 'blueprint deploys linked project and missions');
  [...document.querySelectorAll('#toastRegion .toast button')].at(-1).click();
  await wait(120);
  const revertedBlueprint = await window.asteria.load();
  check(revertedBlueprint.tasks.length === beforeBlueprint.tasks.length, 'blueprint deployment can be undone');
  document.querySelector('#addTemplateButton').click();
  document.querySelector('#templateName').value = 'UI Blueprint';
  document.querySelector('#templateDescription').value = 'Reusable test orbit';
  document.querySelector('#templateTasks').value = 'Collect input\nBuild draft\nReview output';
  document.querySelector('#templateForm').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
  check([...document.querySelectorAll('#templateGrid .template-card')].some((card) => card.textContent.includes('UI Blueprint')), 'custom blueprint can be saved');

  document.querySelector('[data-nexus-tab="health"]').click();
  document.querySelector('#healthScanButton').click();
  await wait(100);
  check(Number(document.querySelector('#healthScore').textContent) >= 0 && Number(document.querySelector('#healthScore').textContent) <= 100, 'workspace health scan calculates a bounded score');
  check(document.querySelector('#diagnosticList').children.length > 0, 'workspace health scan renders actionable diagnostics or healthy state');

  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  document.querySelector('#commandSearch').value = 'Weekly Reset';
  document.querySelector('#commandSearch').dispatchEvent(new Event('input', { bubbles: true }));
  const blueprintSearchResult = [...document.querySelectorAll('#commandResults [data-command]')].find((item) => item.textContent.includes('BLUEPRINT'));
  check(Boolean(blueprintSearchResult), 'global search indexes blueprints alongside workspace data');
  blueprintSearchResult.click();
  check(document.querySelector('#nexusTemplatePanel').classList.contains('active'), 'global search opens the matching blueprint destination');

  document.querySelector('[data-nav="integrations"]').click();
  check(document.querySelector('#integrationsView').classList.contains('active'), 'integration hub navigation works');
  check(document.querySelectorAll('#integrationServices .service-card').length === 6, 'integration hub exposes six service bridges');
  check(document.querySelector('#transferHistory').textContent.trim().length > 0, 'transfer history has an explicit empty or populated state');
  document.querySelector('[data-service="Google Calendar"] [data-exchange-mode="export"]').click();
  check(document.querySelector('#exchangeModal').classList.contains('open') && document.querySelector('#exchangeFormat').value === 'calendarIcs', 'Google Calendar opens an ICS export workflow');
  document.querySelector('#exchangeModal [data-close-exchange]').click();
  document.querySelector('[data-service="Todoist"] [data-exchange-mode="import"]').click();
  check(document.querySelector('#exchangeModal').classList.contains('open') && document.querySelector('#exchangeFormatField').hidden, 'Todoist opens a service-scoped import workflow');
  document.querySelector('#exchangeModal [data-close-exchange]').click();
  const trayEnabled = await window.asteria.setCloseToTray(true);
  const trayDisabled = await window.asteria.setCloseToTray(false);
  check(trayEnabled === true && trayDisabled === false, 'system tray can be enabled and disabled');

  document.querySelector('[data-nav="focus"]').click();
  check(document.querySelector('#focusView').classList.contains('active'), 'focus navigation works');
  document.querySelector('#focusToggleButton').click();
  await wait(1100);
  check(document.querySelector('#focusTimer').textContent === '24:59' || document.querySelector('#focusTimer').textContent === '24:58', 'focus timer counts down');
  await wait(650);
  const persisted = await window.asteria.load();
  check(persisted.focusRuntime.running && persisted.focusRuntime.endAt > Date.now(), 'running timer is persisted');

  await wait(700);
  return { ok: true, checks, count: checks.length };
})()
